### ISSUE TITLE
Is this repository abandoned?

### ISSUE THREAD

**Issue by nicheosala** [grazzolini/mkinitcpio-dropbear#17] opened 2023-06-15 07:11 UTC
The mkinitcpio-dropbear package hasn't received an update in about eight years.
There are issues and pull requests that should be considered.

**Comment by alerque** [comment] 2023-06-15 09:05
Duplicate of #12. My offer there still stands. I suggest closing this and keeping the focus on one issue where discussion and background is already in place.

**Comment by alerque** [comment] 2023-09-11 10:48
The original author apparently doesn't use this any more, but has just added me as a collaborator, and I still use this, so no it is not abandoned. I'll work or facilitating PRs and tinker with improvements going forward until such a time as I no longer use it.

**Closed as completed by alerque** 2023-09-11 10:48 UTC
